#!/usr/bin/python
import sys

if len(sys.argv) < 2:
	print "usage : dotheG 'hello socc!'"
	exit()

word = sys.argv[1]
kat = '.             '
kat2 = '.            <"'
for i in range(len(word)+1):
	kat += '-'
print kat
print kat2 + word + '">'
print kat,

dotheG = '''
.                /
.               /
.      .__++__./
.     /        \\
.    +          +
.    |  / \/ \  |
.    | | O  O | |
.    |*---()---*|
.    | |  O   | |
. -----M------M------
'''
print dotheG
